class Constants

  TRADING_TAX = 0.002
  TRADING_STRANGE_TAX = 0.005
  RUR_AMOUNT_START = 35000

  MIN_ALLOWED_TRADING_WIN_DELTA = 1 # in rur
  TRADING_AMOUNT_IN_BTC = 0.05 # should be more 0.01 anyway
  TRADING_DEFENSE_LIMIT = 10 # in rur
  MIN_ALLOWED_BTC_TRADING_AMOUNT = 0.01
  MIN_PARTIAL_BTC_TRADING_AMOUNT = 0.008

  BTC_RUR = 'btc_rur'
  BTC_USD = 'btc_usd'
  USD_RUR = 'usd_rur'

  TRADING_LOG_FILE = 'log/trading.log'

  COMISSION_ON_BTC_IN  = 0.05
  COMISSION_ON_BTC_OUT = 0.06

end
